export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE ='GET_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const CREATE_PROFILE = 'CREATE_PROFILE'
export const CREATE_LEAD = 'CREATE_LEAD'
export const LEAD_ERROR = 'LEAD_ERROR'

export const GET_LEADS = 'GET_LEADS'
export const GET_LEAD_PROFILE = ' GET_LEAD_PROFILE'

export const PAGINATE = 'PAGINATE'
export const SORT_BY = 'SORT_BY'

export const GET_VENDOR_PROFILE = 'GET_VENDOR_PROFILE'
export const VENDOR_PROFILE_ERROR = 'VENDOR_PROFILE_ERROR'

export const TASKS_ERROR = 'TASKS_ERROR'
export const SET_TASK = 'SET_TASK'
export const GET_TASKS = 'GET_TASKS'
export const CREATE_TASK = 'CREATE_TASK'
